plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.google.gms.google.services)
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

android {
    namespace 'com.example.lockinapp'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.example.lockinapp"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        buildConfigField "String", "GEMINI_API", "\"${localProperties.getProperty('GEMINI_API_KEY')}\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig true // ensure buildconfig generation is enabled
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.firebase.auth
    implementation libs.firebase.database
    implementation("com.github.PhilJay:MPAndroidChart:v3.1.0")

    implementation ("com.google.ai.client.generativeai:generativeai:0.9.0")
    implementation 'com.google.firebase:firebase-storage:20.3.0'
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.firebaseui:firebase-ui-storage:7.2.0'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation fileTree(dir: 'C:\\Android\\sdk\\platforms\\android-36', include: ['*.aar', '*.jar'], exclude: [])

    // CameraX
    def camerax_version = "1.3.0"
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    implementation "androidx.camera:camera-view:${camerax_version}"
}

tasks.register('generateJavadoc', Javadoc) {
    source = android.sourceSets.main.java.srcDirs

    classpath += project.files(android.getBootClasspath())

    android.applicationVariants.all { variant ->
        if (variant.name == 'debug') {
            classpath += variant.javaCompileProvider.get().classpath
        }
    }

    destinationDir = file("${project.buildDir}/javadoc")
    failOnError false
    options.encoding = "UTF-8"

    options.addStringOption('Xdoclint:none', '-quiet')

    doNotTrackState("Ignoring classpath state tracking issues")
}